<a href="https://colab.research.google.com/github/19PA1A0296/AI-lab/blob/master/Exp_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#"Experiment No 1 : Numpy"

##i)Different ways to create Numpy arrays

In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a = np.array([[1,2,3],[10,20,30]])
print(a)

[[ 1  2  3]
 [10 20 30]]


##ii)Add,remove,modify elements in an array

###add

In [ ]:
a = np.array([1,2,3])
b = np.append(a,[98,99,100])
print(b)

[  1   2   3  98  99 100]


###remove

In [ ]:
x = np.delete(a,2)
print (x)

[1 2]


###modify

In [ ]:
x[x<2]=-1
print(x)

[-1  2]


##iii) Arithmetic operations on Numpy array

In [ ]:
import numpy as np
x = ([3,2,1])
y = ([1,2,3])
num_sum = np.add(x,y)
num_diff = np.subtract(x,y)
num_quo = np.divide(x,y)
num_mod = np.mod(x,y)
num_pow = np.power(x,y)
print(num_sum)
print(num_diff)
print(num_quo)
print(num_mod)
print(num_pow)

[4 4 4]
[ 2  0 -2]
[3.         1.         0.33333333]
[0 0 1]
[3 4 1]


##iv) Slicing and iterating of Numpy arrays

###slicing

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:7])

[2 3 4 5 6 7]


###iterating

In [ ]:
for x in arr:
 print(x)

1
2
3
4
5
6
7


##v) Matrix operations on Numpy arrays

In [ ]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[10,20],[30,40]])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.divide(x,y))

[[11 22]
 [33 44]]
[[ -9 -18]
 [-27 -36]]
[[0.1 0.1]
 [0.1 0.1]]
